runtime: python27
api_version: 1
threadsafe: yes

# Codeship required vars (disable these if deploying via local 'gcloud app deploy' command)
# application: mft2017-form
# version: codeship

automatic_scaling:
  min_idle_instances: automatic # idle状態にあるインスタンスの最小値
  max_idle_instances: 1         # idle状態にあるインスタンスの最大値
  min_pending_latency: 3000ms   # リクエストを処理するまでに許される待ち時間の最小
  max_pending_latency: automatic

handlers:
  - url: /static
    static_dir: static
  - url: /favicon\.ico
    static_files: src/favicon.ico
    upload: src/favicon\.ico
  - url: /robots\.txt
    static_files: src/robots.txt
    upload: src/robots\.txt
  - url: /.*
    script: main.app
    secure: always

skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^(.*/)?\.bak$
  - ^(node_modules/.*)

libraries:
  - name: jinja2
    version: latest
