# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo

    docker:
      # - image: circleci/python:2.7.14-browsers
      - image: google/cloud-sdk:alpine

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Python Dependencies
          command: |
            pip install -t lib -r requirements.txt --upgrade

      - save_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - lib

      - run:
          name: System information
          command: |
            echo "Node $(node -v)"
            echo "Yarn v$(yarn --version)"

      # - run:
      #     name: Install Node Dependencies
      #     command: |
      #       yarn install

      # - save_cache:
      #     key: v1-dependencies-{{ checksum "yarn.lock" }}
      #     paths:
      #       - node_modules

      - store_artifacts:
          path: test-reports
          destination: test-reports

  deploy:
    docker:
      - image: google/cloud-sdk

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Authenticate and Set Project ID
          command: |
            echo $GCP_SERVICE_ACCOUNT_KEY | base64 -i --decode > "$HOME/gcp-service-account-key.json"
            gcloud auth activate-service-account --key-file "$HOME/gcp-service-account-key.json"
            gcloud --quiet config set project make-jp

      - run:
          name: Deploy to GAE
          command: |
            gcloud --quiet app deploy app.yaml --version $(echo $CIRCLE_BRANCH | sed "s/\//\-/g")
          no_output_timeout: 20m

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
