# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo

    docker:
      # - image: circleci/python:2.7.14-browsers
      - image: google/cloud-sdk

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            pip install -t lib -r requirements.txt --upgrade

      - save_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - ./lib

      - run:
          name: Hello world!
          command: |
            echo 'Hello world!'

      - run:
          name: Check CIRCLE_BRANCH
          command: |
            echo 'Hello world!'

      - run:
          name: Check GCP_SERVICE_ACCOUNT_KEY
          command: |
            echo $GCP_SERVICE_ACCOUNT_KEY | base64 -i --decode > "$HOME/gcp-service-account-key.json"
            gcloud auth activate-service-account --key-file "$HOME/gcp-service-account-key.json"
            gcloud --quiet config set project make-jp
            gcloud --quiet app deploy app.yaml --version $(echo $CIRCLE_BRANCH | sed "s/\//\-/g")
          no_output_timeout: 20m

      - store_artifacts:
          path: test-reports
          destination: test-reports
